export const surpriseMePrompts = [
  "Uma cadeira no formato de um abacate",
  "uma pintura surrealista em óleo de Salvador Dalí de um gato jogando damas",
  "ursos de pelúcia fazendo compras de comida no Japão, ukiyo-e",
  "uma pintura em óleo de Matisse de um robô humanóide jogando xadrez",
  "panda cientista louco misturando químicos reluzentes, arte digital",
  "uma fotografia macro de 35mm de dois ratos no Havaí, cada um usando roupas de banho minúsculas e carregando pranchas de surf minúsculas, arte digital",
  "renderização 3D de um peixe tropical fofo em um aquário com fundo azul escuro, arte digital",
  "um astronauta relaxando em um resort tropical no espaço, vaporwave",
  "um retrato em óleo de uma capivara usando trajes medievais reais e uma coroa ornada em um fundo escuro",
  "uma janela de vitral mostrando um hambúrguer e batatas fritas",
  "um desenho a lápis e aquarela de uma cidade brilhante no futuro com carros voadores",
  "uma área de lounge interna iluminada pelo sol com uma piscina de água clara e outra piscina com água rosa translúcida, ao lado de uma grande janela, arte digital",
  "um shiba inu que diz a sorte lendo seu destino em um hambúrguer gigante, arte digital",
  "um pirulito com uma brincos de pérola de Johannes Vermeer",
  "um desenho em pastel a óleo de um gato irritado em uma nave espacial",
  "uma pintura de uma raposa no estilo da Noite Estrelada",
  "uma tigela de sopa que parece um monstro, tricotado de lã",
  "Um brinquedo de pelúcia robô sentado contra uma parede amarela",
  "um pôr-do-sol no estilo synthwave acima da água reflexiva do mar, arte digital",
  "duas torres futuristas com uma ponte aérea coberta de vegetação exuberante, arte digital",
  "uma renderização 3D de um balão de ar quente colorido como um arco-íris voando acima de um lago reflexivo",
  "uma capa de quadrinhos de um super-herói usando fones de ouvido",
  "uma explosão colorida de pó no centro de um fundo preto",
  "uma foto de um cachorro Samoyed com a língua para fora abraçando um gato Siamese branco",
  "uma foto de um monstro de pelo branco em uma sala roxa",
  "um gato montado em uma banana voando pelo espaço",
  ];